theme: minima
title: Hello Worldw
author: sakeyehp
email: sakeyehp@yahoo.co.uk
description: > # this means to ignore newlines until "baseurl:"
 This is all you need to know about Kayode SAKEYE. One blog post at a time.
# social links
twitter_username: Sir_Pencil # DO NOT include the @ character, or else the build will fail!
github_username:  sakeyehp # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
